channels:
- conda-forge
dependencies:
- python=3.13.7
- pip<=25.2
- pip:
  - mlflow==3.3.2
  - cloudpickle==3.1.1
  - numpy==2.1.1
  - pandas==2.2.2
  - psutil==7.0.0
  - scikit-learn==1.5.2
  - scipy==1.16.1
name: mlflow-env
